name: countries_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  dio: ^5.3.2
  flutter:
    sdk: flutter
  otp_text_field: ^1.1.3
  otp_timer_button: ^1.1.0

  flutter_localizations:
    sdk: flutter
  intl: any
  hive:
  hive_flutter:
  locator: ^0.0.0-dev.2
  get_it: ^7.6.0
  provider: ^6.0.5
  path_provider: ^2.0.2
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator:
  build_runner:

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - lib/i18n/
    - lib/l10n/
